# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawOtPsClient, RawOtPsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OtPsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOtPsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOtPsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOtPsClient
        """
        return self._raw_client

    def request_otp_for_quote_verification(
        self, *, email: str, phone: str, owner_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        This endpoint sends a one-time password (OTP) to the provided email and phone number for quote verification. It should be called before creating a quote request.

        Parameters
        ----------
        email : str
            Email address of the car owner

        phone : str
            Phone number starting with 05 and containing 10 digits

        owner_id : str
            National ID or Iqama ID of the car owner (10 digits)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.ot_ps.request_otp_for_quote_verification(
            email="someone@example.com",
            phone="0501234567",
            owner_id="1012345678",
        )
        """
        _response = self._raw_client.request_otp_for_quote_verification(
            email=email, phone=phone, owner_id=owner_id, request_options=request_options
        )
        return _response.data

    def request_otp_for_issuing_policy(
        self,
        *,
        email: str,
        phone: str,
        owner_id: str,
        quote_request_id: int,
        quote_reference_id: str,
        quote_price_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint sends a one-time password (OTP). It should be called before issuing a policy.

        Parameters
        ----------
        email : str
            Email address of the car owner

        phone : str
            Phone number starting with 05 and containing 10 digits

        owner_id : str
            National ID or Iqama ID of the car owner (10 digits)

        quote_request_id : int
            ID of the car quote request

        quote_reference_id : str
            Unique identifier for the quote reference ID (coming from POST /quote-requests)

        quote_price_id : str
            Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.ot_ps.request_otp_for_issuing_policy(
            email="someone@example.com",
            phone="0501234567",
            owner_id="1012345678",
            quote_request_id=123,
            quote_reference_id="550e8400-e29b-41d4-a716-446655440000",
            quote_price_id="550e8400-e29b-41d4-a716-446655440001",
        )
        """
        _response = self._raw_client.request_otp_for_issuing_policy(
            email=email,
            phone=phone,
            owner_id=owner_id,
            quote_request_id=quote_request_id,
            quote_reference_id=quote_reference_id,
            quote_price_id=quote_price_id,
            request_options=request_options,
        )
        return _response.data


class AsyncOtPsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOtPsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOtPsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOtPsClient
        """
        return self._raw_client

    async def request_otp_for_quote_verification(
        self, *, email: str, phone: str, owner_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        This endpoint sends a one-time password (OTP) to the provided email and phone number for quote verification. It should be called before creating a quote request.

        Parameters
        ----------
        email : str
            Email address of the car owner

        phone : str
            Phone number starting with 05 and containing 10 digits

        owner_id : str
            National ID or Iqama ID of the car owner (10 digits)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ot_ps.request_otp_for_quote_verification(
                email="someone@example.com",
                phone="0501234567",
                owner_id="1012345678",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.request_otp_for_quote_verification(
            email=email, phone=phone, owner_id=owner_id, request_options=request_options
        )
        return _response.data

    async def request_otp_for_issuing_policy(
        self,
        *,
        email: str,
        phone: str,
        owner_id: str,
        quote_request_id: int,
        quote_reference_id: str,
        quote_price_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        This endpoint sends a one-time password (OTP). It should be called before issuing a policy.

        Parameters
        ----------
        email : str
            Email address of the car owner

        phone : str
            Phone number starting with 05 and containing 10 digits

        owner_id : str
            National ID or Iqama ID of the car owner (10 digits)

        quote_request_id : int
            ID of the car quote request

        quote_reference_id : str
            Unique identifier for the quote reference ID (coming from POST /quote-requests)

        quote_price_id : str
            Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ot_ps.request_otp_for_issuing_policy(
                email="someone@example.com",
                phone="0501234567",
                owner_id="1012345678",
                quote_request_id=123,
                quote_reference_id="550e8400-e29b-41d4-a716-446655440000",
                quote_price_id="550e8400-e29b-41d4-a716-446655440001",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.request_otp_for_issuing_policy(
            email=email,
            phone=phone,
            owner_id=owner_id,
            quote_request_id=quote_request_id,
            quote_reference_id=quote_reference_id,
            quote_price_id=quote_price_id,
            request_options=request_options,
        )
        return _response.data
