# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        BadRequestErrorBody,
        Benefit,
        CompanyQuote,
        Error,
        Policy,
        QuotePrice,
        QuoteResponse,
        QuoteResponseDriversItem,
        QuoteResponseQuotesItem,
        UnauthorizedErrorBody,
    )
    from .errors import BadRequestError, NotFoundError, UnauthorizedError, UnprocessableEntityError
    from . import ot_ps, policies, quotes
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncYasminaaiApi, YasminaaiApi
    from .environment import YasminaaiApiEnvironment
    from .quotes import (
        DeleteQuoteRequestsIdResponse,
        GetQuoteRequestsResponse,
        GetQuoteRequestsResponseLinksItem,
        PostQuoteRequestsRequestDriversItem,
    )
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncYasminaaiApi": ".client",
    "BadRequestError": ".errors",
    "BadRequestErrorBody": ".types",
    "Benefit": ".types",
    "CompanyQuote": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "DeleteQuoteRequestsIdResponse": ".quotes",
    "Error": ".types",
    "GetQuoteRequestsResponse": ".quotes",
    "GetQuoteRequestsResponseLinksItem": ".quotes",
    "NotFoundError": ".errors",
    "Policy": ".types",
    "PostQuoteRequestsRequestDriversItem": ".quotes",
    "QuotePrice": ".types",
    "QuoteResponse": ".types",
    "QuoteResponseDriversItem": ".types",
    "QuoteResponseQuotesItem": ".types",
    "UnauthorizedError": ".errors",
    "UnauthorizedErrorBody": ".types",
    "UnprocessableEntityError": ".errors",
    "YasminaaiApi": ".client",
    "YasminaaiApiEnvironment": ".environment",
    "__version__": ".version",
    "ot_ps": ".ot_ps",
    "policies": ".policies",
    "quotes": ".quotes",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncYasminaaiApi",
    "BadRequestError",
    "BadRequestErrorBody",
    "Benefit",
    "CompanyQuote",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "DeleteQuoteRequestsIdResponse",
    "Error",
    "GetQuoteRequestsResponse",
    "GetQuoteRequestsResponseLinksItem",
    "NotFoundError",
    "Policy",
    "PostQuoteRequestsRequestDriversItem",
    "QuotePrice",
    "QuoteResponse",
    "QuoteResponseDriversItem",
    "QuoteResponseQuotesItem",
    "UnauthorizedError",
    "UnauthorizedErrorBody",
    "UnprocessableEntityError",
    "YasminaaiApi",
    "YasminaaiApiEnvironment",
    "__version__",
    "ot_ps",
    "policies",
    "quotes",
]
