# This file was auto-generated by Fern from our API Definition.

import enum


class YasminaaiApiEnvironment(enum.Enum):
    SANDBOX = "https://sandbox.yasmina.ai/api/v1/car-comp"
    PRODUCTION = "https://production.yasmina.ai/api/v1/car-comp"
