# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.paginated_quote_response import PaginatedQuoteResponse
from ..types.quote_response import QuoteResponse
from .raw_client import AsyncRawQuotesClient, RawQuotesClient
from .types.delete_quote_requests_id_response import DeleteQuoteRequestsIdResponse
from .types.post_quote_requests_request_accept_language import PostQuoteRequestsRequestAcceptLanguage
from .types.post_quote_requests_request_drivers_item import PostQuoteRequestsRequestDriversItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class QuotesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawQuotesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawQuotesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawQuotesClient
        """
        return self._raw_client

    def show_quote(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> QuoteResponse:
        """
        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QuoteResponse
            Single quote details

        Examples
        --------
        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.quotes.show_quote(
            id=1,
        )
        """
        _response = self._raw_client.show_quote(id, request_options=request_options)
        return _response.data

    def delete_quote(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteQuoteRequestsIdResponse:
        """
        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteQuoteRequestsIdResponse
            Quote deleted successfully

        Examples
        --------
        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.quotes.delete_quote(
            id=1,
        )
        """
        _response = self._raw_client.delete_quote(id, request_options=request_options)
        return _response.data

    def list_quotes(
        self,
        *,
        date_from: typing.Optional[dt.date] = None,
        date_to: typing.Optional[dt.date] = None,
        per_page: typing.Optional[int] = None,
        include_aggregates: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedQuoteResponse:
        """
        Parameters
        ----------
        date_from : typing.Optional[dt.date]
            Inclusive lower bound for quote request creation date.

        date_to : typing.Optional[dt.date]
            Inclusive upper bound for quote request creation date.

        per_page : typing.Optional[int]
            Number of quote requests to return per page.

        include_aggregates : typing.Optional[bool]
            When true, includes quote request totals and monthly buckets for the filtered result set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedQuoteResponse
            Paginated list of quotes

        Examples
        --------
        import datetime

        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.quotes.list_quotes(
            date_from=datetime.date.fromisoformat(
                "2026-06-01",
            ),
            date_to=datetime.date.fromisoformat(
                "2026-06-30",
            ),
            per_page=10,
            include_aggregates=True,
        )
        """
        _response = self._raw_client.list_quotes(
            date_from=date_from,
            date_to=date_to,
            per_page=per_page,
            include_aggregates=include_aggregates,
            request_options=request_options,
        )
        return _response.data

    def request_quotes(
        self,
        *,
        otp: str,
        owner_id: str,
        phone: str,
        birthdate: dt.date,
        car_estimated_cost: float,
        accept_language: typing.Optional[PostQuoteRequestsRequestAcceptLanguage] = None,
        email: typing.Optional[str] = OMIT,
        car_sequence_number: typing.Optional[str] = OMIT,
        custom_number: typing.Optional[str] = OMIT,
        is_ownership_transfer: typing.Optional[bool] = OMIT,
        current_car_owner_id: typing.Optional[str] = OMIT,
        car_model_year: typing.Optional[int] = OMIT,
        start_date: typing.Optional[dt.date] = OMIT,
        drivers: typing.Optional[typing.Sequence[PostQuoteRequestsRequestDriversItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QuoteResponse:
        """
        For getting prices with benefits.
        The Quote IDs can be used later to issue a policy

        Parameters
        ----------
        otp : str
            The OTP received by the customer from the Request OTP API

        owner_id : str
            Owner ID must be 10 digits starting with 1, 2, or 7

        phone : str
            Phone number must start with 05 and be 10 digits

        birthdate : dt.date
            Birthdate in YYYY-MM-DD format

        car_estimated_cost : float
            Estimated cost of the car

        accept_language : typing.Optional[PostQuoteRequestsRequestAcceptLanguage]
            Set to ar to receive Arabic-localized quote content.

        email : typing.Optional[str]
            Email address must be valid and belongs to the customer

        car_sequence_number : typing.Optional[str]
            Car sequence number must be 8 or 9 digits

        custom_number : typing.Optional[str]
            Custom car number between 1000000 and 9999999999 (for newly imported cars)

        is_ownership_transfer : typing.Optional[bool]
            Indicates if the ownership is being transferred

        current_car_owner_id : typing.Optional[str]
            Required if is_ownership_transfer is true; 10 digits starting with 1,2,7

        car_model_year : typing.Optional[int]
            Car model year between 1950 and next year

        start_date : typing.Optional[dt.date]
            Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.

        drivers : typing.Optional[typing.Sequence[PostQuoteRequestsRequestDriversItem]]
            List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QuoteResponse
            Insurance quote details

        Examples
        --------
        import datetime

        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.quotes.request_quotes(
            otp="123456",
            owner_id="owner_id",
            phone="phone",
            birthdate=datetime.date.fromisoformat(
                "2023-01-15",
            ),
            car_estimated_cost=1.1,
        )
        """
        _response = self._raw_client.request_quotes(
            otp=otp,
            owner_id=owner_id,
            phone=phone,
            birthdate=birthdate,
            car_estimated_cost=car_estimated_cost,
            accept_language=accept_language,
            email=email,
            car_sequence_number=car_sequence_number,
            custom_number=custom_number,
            is_ownership_transfer=is_ownership_transfer,
            current_car_owner_id=current_car_owner_id,
            car_model_year=car_model_year,
            start_date=start_date,
            drivers=drivers,
            request_options=request_options,
        )
        return _response.data


class AsyncQuotesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawQuotesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawQuotesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawQuotesClient
        """
        return self._raw_client

    async def show_quote(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> QuoteResponse:
        """
        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QuoteResponse
            Single quote details

        Examples
        --------
        import asyncio

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.quotes.show_quote(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.show_quote(id, request_options=request_options)
        return _response.data

    async def delete_quote(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteQuoteRequestsIdResponse:
        """
        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteQuoteRequestsIdResponse
            Quote deleted successfully

        Examples
        --------
        import asyncio

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.quotes.delete_quote(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_quote(id, request_options=request_options)
        return _response.data

    async def list_quotes(
        self,
        *,
        date_from: typing.Optional[dt.date] = None,
        date_to: typing.Optional[dt.date] = None,
        per_page: typing.Optional[int] = None,
        include_aggregates: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedQuoteResponse:
        """
        Parameters
        ----------
        date_from : typing.Optional[dt.date]
            Inclusive lower bound for quote request creation date.

        date_to : typing.Optional[dt.date]
            Inclusive upper bound for quote request creation date.

        per_page : typing.Optional[int]
            Number of quote requests to return per page.

        include_aggregates : typing.Optional[bool]
            When true, includes quote request totals and monthly buckets for the filtered result set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedQuoteResponse
            Paginated list of quotes

        Examples
        --------
        import asyncio
        import datetime

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.quotes.list_quotes(
                date_from=datetime.date.fromisoformat(
                    "2026-06-01",
                ),
                date_to=datetime.date.fromisoformat(
                    "2026-06-30",
                ),
                per_page=10,
                include_aggregates=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_quotes(
            date_from=date_from,
            date_to=date_to,
            per_page=per_page,
            include_aggregates=include_aggregates,
            request_options=request_options,
        )
        return _response.data

    async def request_quotes(
        self,
        *,
        otp: str,
        owner_id: str,
        phone: str,
        birthdate: dt.date,
        car_estimated_cost: float,
        accept_language: typing.Optional[PostQuoteRequestsRequestAcceptLanguage] = None,
        email: typing.Optional[str] = OMIT,
        car_sequence_number: typing.Optional[str] = OMIT,
        custom_number: typing.Optional[str] = OMIT,
        is_ownership_transfer: typing.Optional[bool] = OMIT,
        current_car_owner_id: typing.Optional[str] = OMIT,
        car_model_year: typing.Optional[int] = OMIT,
        start_date: typing.Optional[dt.date] = OMIT,
        drivers: typing.Optional[typing.Sequence[PostQuoteRequestsRequestDriversItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QuoteResponse:
        """
        For getting prices with benefits.
        The Quote IDs can be used later to issue a policy

        Parameters
        ----------
        otp : str
            The OTP received by the customer from the Request OTP API

        owner_id : str
            Owner ID must be 10 digits starting with 1, 2, or 7

        phone : str
            Phone number must start with 05 and be 10 digits

        birthdate : dt.date
            Birthdate in YYYY-MM-DD format

        car_estimated_cost : float
            Estimated cost of the car

        accept_language : typing.Optional[PostQuoteRequestsRequestAcceptLanguage]
            Set to ar to receive Arabic-localized quote content.

        email : typing.Optional[str]
            Email address must be valid and belongs to the customer

        car_sequence_number : typing.Optional[str]
            Car sequence number must be 8 or 9 digits

        custom_number : typing.Optional[str]
            Custom car number between 1000000 and 9999999999 (for newly imported cars)

        is_ownership_transfer : typing.Optional[bool]
            Indicates if the ownership is being transferred

        current_car_owner_id : typing.Optional[str]
            Required if is_ownership_transfer is true; 10 digits starting with 1,2,7

        car_model_year : typing.Optional[int]
            Car model year between 1950 and next year

        start_date : typing.Optional[dt.date]
            Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.

        drivers : typing.Optional[typing.Sequence[PostQuoteRequestsRequestDriversItem]]
            List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QuoteResponse
            Insurance quote details

        Examples
        --------
        import asyncio
        import datetime

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.quotes.request_quotes(
                otp="123456",
                owner_id="owner_id",
                phone="phone",
                birthdate=datetime.date.fromisoformat(
                    "2023-01-15",
                ),
                car_estimated_cost=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.request_quotes(
            otp=otp,
            owner_id=owner_id,
            phone=phone,
            birthdate=birthdate,
            car_estimated_cost=car_estimated_cost,
            accept_language=accept_language,
            email=email,
            car_sequence_number=car_sequence_number,
            custom_number=custom_number,
            is_ownership_transfer=is_ownership_transfer,
            current_car_owner_id=current_car_owner_id,
            car_model_year=car_model_year,
            start_date=start_date,
            drivers=drivers,
            request_options=request_options,
        )
        return _response.data
