# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.paginated_quote_response import PaginatedQuoteResponse
from ..types.quote_response import QuoteResponse
from .types.delete_quote_requests_id_response import DeleteQuoteRequestsIdResponse
from .types.post_quote_requests_request_accept_language import PostQuoteRequestsRequestAcceptLanguage
from .types.post_quote_requests_request_drivers_item import PostQuoteRequestsRequestDriversItem
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawQuotesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def show_quote(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[QuoteResponse]:
        """
        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[QuoteResponse]
            Single quote details
        """
        _response = self._client_wrapper.httpx_client.request(
            f"quote-requests/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QuoteResponse,
                    parse_obj_as(
                        type_=QuoteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_quote(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeleteQuoteRequestsIdResponse]:
        """
        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeleteQuoteRequestsIdResponse]
            Quote deleted successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"quote-requests/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteQuoteRequestsIdResponse,
                    parse_obj_as(
                        type_=DeleteQuoteRequestsIdResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_quotes(
        self,
        *,
        date_from: typing.Optional[dt.date] = None,
        date_to: typing.Optional[dt.date] = None,
        per_page: typing.Optional[int] = None,
        include_aggregates: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedQuoteResponse]:
        """
        Parameters
        ----------
        date_from : typing.Optional[dt.date]
            Inclusive lower bound for quote request creation date.

        date_to : typing.Optional[dt.date]
            Inclusive upper bound for quote request creation date.

        per_page : typing.Optional[int]
            Number of quote requests to return per page.

        include_aggregates : typing.Optional[bool]
            When true, includes quote request totals and monthly buckets for the filtered result set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedQuoteResponse]
            Paginated list of quotes
        """
        _response = self._client_wrapper.httpx_client.request(
            "quote-requests",
            method="GET",
            params={
                "date_from": str(date_from) if date_from is not None else None,
                "date_to": str(date_to) if date_to is not None else None,
                "per_page": per_page,
                "include_aggregates": include_aggregates,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedQuoteResponse,
                    parse_obj_as(
                        type_=PaginatedQuoteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def request_quotes(
        self,
        *,
        otp: str,
        owner_id: str,
        phone: str,
        birthdate: dt.date,
        car_estimated_cost: float,
        accept_language: typing.Optional[PostQuoteRequestsRequestAcceptLanguage] = None,
        email: typing.Optional[str] = OMIT,
        car_sequence_number: typing.Optional[str] = OMIT,
        custom_number: typing.Optional[str] = OMIT,
        is_ownership_transfer: typing.Optional[bool] = OMIT,
        current_car_owner_id: typing.Optional[str] = OMIT,
        car_model_year: typing.Optional[int] = OMIT,
        start_date: typing.Optional[dt.date] = OMIT,
        drivers: typing.Optional[typing.Sequence[PostQuoteRequestsRequestDriversItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[QuoteResponse]:
        """
        For getting prices with benefits.
        The Quote IDs can be used later to issue a policy

        Parameters
        ----------
        otp : str
            The OTP received by the customer from the Request OTP API

        owner_id : str
            Owner ID must be 10 digits starting with 1, 2, or 7

        phone : str
            Phone number must start with 05 and be 10 digits

        birthdate : dt.date
            Birthdate in YYYY-MM-DD format

        car_estimated_cost : float
            Estimated cost of the car

        accept_language : typing.Optional[PostQuoteRequestsRequestAcceptLanguage]
            Set to ar to receive Arabic-localized quote content.

        email : typing.Optional[str]
            Email address must be valid and belongs to the customer

        car_sequence_number : typing.Optional[str]
            Car sequence number must be 8 or 9 digits

        custom_number : typing.Optional[str]
            Custom car number between 1000000 and 9999999999 (for newly imported cars)

        is_ownership_transfer : typing.Optional[bool]
            Indicates if the ownership is being transferred

        current_car_owner_id : typing.Optional[str]
            Required if is_ownership_transfer is true; 10 digits starting with 1,2,7

        car_model_year : typing.Optional[int]
            Car model year between 1950 and next year

        start_date : typing.Optional[dt.date]
            Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.

        drivers : typing.Optional[typing.Sequence[PostQuoteRequestsRequestDriversItem]]
            List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[QuoteResponse]
            Insurance quote details
        """
        _response = self._client_wrapper.httpx_client.request(
            "quote-requests",
            method="POST",
            json={
                "otp": otp,
                "owner_id": owner_id,
                "email": email,
                "phone": phone,
                "birthdate": birthdate,
                "car_sequence_number": car_sequence_number,
                "custom_number": custom_number,
                "is_ownership_transfer": is_ownership_transfer,
                "current_car_owner_id": current_car_owner_id,
                "car_estimated_cost": car_estimated_cost,
                "car_model_year": car_model_year,
                "start_date": start_date,
                "drivers": convert_and_respect_annotation_metadata(
                    object_=drivers, annotation=typing.Sequence[PostQuoteRequestsRequestDriversItem], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QuoteResponse,
                    parse_obj_as(
                        type_=QuoteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawQuotesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def show_quote(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[QuoteResponse]:
        """
        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[QuoteResponse]
            Single quote details
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"quote-requests/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QuoteResponse,
                    parse_obj_as(
                        type_=QuoteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_quote(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeleteQuoteRequestsIdResponse]:
        """
        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeleteQuoteRequestsIdResponse]
            Quote deleted successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"quote-requests/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteQuoteRequestsIdResponse,
                    parse_obj_as(
                        type_=DeleteQuoteRequestsIdResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_quotes(
        self,
        *,
        date_from: typing.Optional[dt.date] = None,
        date_to: typing.Optional[dt.date] = None,
        per_page: typing.Optional[int] = None,
        include_aggregates: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedQuoteResponse]:
        """
        Parameters
        ----------
        date_from : typing.Optional[dt.date]
            Inclusive lower bound for quote request creation date.

        date_to : typing.Optional[dt.date]
            Inclusive upper bound for quote request creation date.

        per_page : typing.Optional[int]
            Number of quote requests to return per page.

        include_aggregates : typing.Optional[bool]
            When true, includes quote request totals and monthly buckets for the filtered result set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedQuoteResponse]
            Paginated list of quotes
        """
        _response = await self._client_wrapper.httpx_client.request(
            "quote-requests",
            method="GET",
            params={
                "date_from": str(date_from) if date_from is not None else None,
                "date_to": str(date_to) if date_to is not None else None,
                "per_page": per_page,
                "include_aggregates": include_aggregates,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedQuoteResponse,
                    parse_obj_as(
                        type_=PaginatedQuoteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def request_quotes(
        self,
        *,
        otp: str,
        owner_id: str,
        phone: str,
        birthdate: dt.date,
        car_estimated_cost: float,
        accept_language: typing.Optional[PostQuoteRequestsRequestAcceptLanguage] = None,
        email: typing.Optional[str] = OMIT,
        car_sequence_number: typing.Optional[str] = OMIT,
        custom_number: typing.Optional[str] = OMIT,
        is_ownership_transfer: typing.Optional[bool] = OMIT,
        current_car_owner_id: typing.Optional[str] = OMIT,
        car_model_year: typing.Optional[int] = OMIT,
        start_date: typing.Optional[dt.date] = OMIT,
        drivers: typing.Optional[typing.Sequence[PostQuoteRequestsRequestDriversItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[QuoteResponse]:
        """
        For getting prices with benefits.
        The Quote IDs can be used later to issue a policy

        Parameters
        ----------
        otp : str
            The OTP received by the customer from the Request OTP API

        owner_id : str
            Owner ID must be 10 digits starting with 1, 2, or 7

        phone : str
            Phone number must start with 05 and be 10 digits

        birthdate : dt.date
            Birthdate in YYYY-MM-DD format

        car_estimated_cost : float
            Estimated cost of the car

        accept_language : typing.Optional[PostQuoteRequestsRequestAcceptLanguage]
            Set to ar to receive Arabic-localized quote content.

        email : typing.Optional[str]
            Email address must be valid and belongs to the customer

        car_sequence_number : typing.Optional[str]
            Car sequence number must be 8 or 9 digits

        custom_number : typing.Optional[str]
            Custom car number between 1000000 and 9999999999 (for newly imported cars)

        is_ownership_transfer : typing.Optional[bool]
            Indicates if the ownership is being transferred

        current_car_owner_id : typing.Optional[str]
            Required if is_ownership_transfer is true; 10 digits starting with 1,2,7

        car_model_year : typing.Optional[int]
            Car model year between 1950 and next year

        start_date : typing.Optional[dt.date]
            Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.

        drivers : typing.Optional[typing.Sequence[PostQuoteRequestsRequestDriversItem]]
            List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[QuoteResponse]
            Insurance quote details
        """
        _response = await self._client_wrapper.httpx_client.request(
            "quote-requests",
            method="POST",
            json={
                "otp": otp,
                "owner_id": owner_id,
                "email": email,
                "phone": phone,
                "birthdate": birthdate,
                "car_sequence_number": car_sequence_number,
                "custom_number": custom_number,
                "is_ownership_transfer": is_ownership_transfer,
                "current_car_owner_id": current_car_owner_id,
                "car_estimated_cost": car_estimated_cost,
                "car_model_year": car_model_year,
                "start_date": start_date,
                "drivers": convert_and_respect_annotation_metadata(
                    object_=drivers, annotation=typing.Sequence[PostQuoteRequestsRequestDriversItem], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QuoteResponse,
                    parse_obj_as(
                        type_=QuoteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
