# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .bad_request_error_body import BadRequestErrorBody
    from .benefit import Benefit
    from .company_quote import CompanyQuote
    from .company_quote_type import CompanyQuoteType
    from .error import Error
    from .paginated_policy_response import PaginatedPolicyResponse
    from .paginated_quote_response import PaginatedQuoteResponse
    from .pagination_link import PaginationLink
    from .policy import Policy
    from .policy_aggregates import PolicyAggregates
    from .policy_month_aggregate import PolicyMonthAggregate
    from .quote_price import QuotePrice
    from .quote_request_aggregates import QuoteRequestAggregates
    from .quote_response import QuoteResponse
    from .quote_response_drivers_item import QuoteResponseDriversItem
    from .quote_response_quotes_item import QuoteResponseQuotesItem
    from .quote_response_quotes_item_type import QuoteResponseQuotesItemType
    from .unauthorized_error_body import UnauthorizedErrorBody
_dynamic_imports: typing.Dict[str, str] = {
    "BadRequestErrorBody": ".bad_request_error_body",
    "Benefit": ".benefit",
    "CompanyQuote": ".company_quote",
    "CompanyQuoteType": ".company_quote_type",
    "Error": ".error",
    "PaginatedPolicyResponse": ".paginated_policy_response",
    "PaginatedQuoteResponse": ".paginated_quote_response",
    "PaginationLink": ".pagination_link",
    "Policy": ".policy",
    "PolicyAggregates": ".policy_aggregates",
    "PolicyMonthAggregate": ".policy_month_aggregate",
    "QuotePrice": ".quote_price",
    "QuoteRequestAggregates": ".quote_request_aggregates",
    "QuoteResponse": ".quote_response",
    "QuoteResponseDriversItem": ".quote_response_drivers_item",
    "QuoteResponseQuotesItem": ".quote_response_quotes_item",
    "QuoteResponseQuotesItemType": ".quote_response_quotes_item_type",
    "UnauthorizedErrorBody": ".unauthorized_error_body",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BadRequestErrorBody",
    "Benefit",
    "CompanyQuote",
    "CompanyQuoteType",
    "Error",
    "PaginatedPolicyResponse",
    "PaginatedQuoteResponse",
    "PaginationLink",
    "Policy",
    "PolicyAggregates",
    "PolicyMonthAggregate",
    "QuotePrice",
    "QuoteRequestAggregates",
    "QuoteResponse",
    "QuoteResponseDriversItem",
    "QuoteResponseQuotesItem",
    "QuoteResponseQuotesItemType",
    "UnauthorizedErrorBody",
]
