# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .policy_month_aggregate import PolicyMonthAggregate


class PolicyAggregates(UniversalBaseModel):
    """
    Returned only when include_aggregates is true.
    """

    total_count: typing.Optional[int] = None
    total_price: typing.Optional[float] = None
    by_month: typing.Optional[typing.Dict[str, PolicyMonthAggregate]] = pydantic.Field(default=None)
    """
    Monthly policy counts and sales totals keyed by YYYY-MM. For issued policies (`status=1`), buckets use `uploaded_at` and fall back to `created_at`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
