# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Policy(UniversalBaseModel):
    id: typing.Optional[int] = None
    meta_data: typing.Optional[typing.Dict[str, typing.Any]] = None
    start_date: typing.Optional[str] = None
    provider_policy_id: typing.Optional[int] = None
    provider_policy: typing.Optional[str] = None
    order_status: typing.Optional[int] = None
    approval_status: typing.Optional[int] = None
    end_date: typing.Optional[str] = None
    is_claimed: typing.Optional[bool] = None
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    client_id: typing.Optional[str] = None
    canceled_at: typing.Optional[str] = None
    invoice: typing.Optional[str] = None
    cancellation_document: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
