# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class QuoteResponseDriversItem(UniversalBaseModel):
    owner_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Driver's national ID (10 digits starting with 1, 2, or 7)
    """

    birthdate: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Driver's birthdate in YYYY-MM-DD format
    """

    driving_percentage: typing.Optional[int] = pydantic.Field(default=None)
    """
    Percentage of driving for this driver (25, 50, 75, or 100)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
