# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class QuoteRequestAggregates(UniversalBaseModel):
    """
    Returned only when include_aggregates is true.
    """

    total_count: typing.Optional[int] = None
    by_month: typing.Optional[typing.Dict[str, int]] = pydantic.Field(default=None)
    """
    Monthly quote request counts keyed by YYYY-MM.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
