# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .quote_response_drivers_item import QuoteResponseDriversItem
from .quote_response_quotes_item import QuoteResponseQuotesItem


class QuoteResponse(UniversalBaseModel):
    owner_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The owner’s national ID or Iqama ID
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    The owner's phone number
    """

    birthdate: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    The owner's birthdate. Hijri for Saudi nationals, Gregorian for others
    """

    car_sequence_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    The car sequence number from 9 digits
    """

    is_ownership_transfer: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether it was a car transfer or not
    """

    car_estimated_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    The estimated cost of the car
    """

    car_model_year: typing.Optional[int] = pydantic.Field(default=None)
    """
    The car model year
    """

    start_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Requested policy start date in YYYY-MM-DD. Returned if provided in the quote request.
    """

    drivers: typing.Optional[typing.List[QuoteResponseDriversItem]] = pydantic.Field(default=None)
    """
    List of drivers associated with this quote request. Returned if drivers were provided in the request.
    """

    quotes: typing.Optional[typing.List[QuoteResponseQuotesItem]] = pydantic.Field(default=None)
    """
    An array representing each insurance company quote. Each item has the company name, the prices, and the benefits.
    """

    client_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Your own client ID
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    In case of an update on this quote, this date will change
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When was the quote requested
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Yasmina ID for the quote. You can use it to delete items or showing it again to the customer
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
