# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .benefit import Benefit
from .quote_price import QuotePrice


class QuoteResponseQuotesItem(UniversalBaseModel):
    company_name: typing.Optional[str] = None
    prices: typing.Optional[typing.List[QuotePrice]] = pydantic.Field(default=None)
    """
    An array representing each price. This will have the premium and the deductible
    """

    benefits: typing.Optional[typing.List[Benefit]] = pydantic.Field(default=None)
    """
    An array representing the different benefits offered by the company. Some of them are free and comes with the insurance, some are paid and optional
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
