# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class QuotePrice(UniversalBaseModel):
    quote_price_id: typing.Optional[str] = None
    deductible: typing.Optional[float] = None
    subtotal: typing.Optional[float] = None
    vat_percentage: typing.Optional[float] = None
    vat: typing.Optional[float] = None
    total: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
