# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PostQuoteRequestsRequestDriversItem(UniversalBaseModel):
    owner_id: str = pydantic.Field()
    """
    Driver's national ID. Must be 10 digits starting with 1, 2, or 7.
    """

    birthdate: dt.date = pydantic.Field()
    """
    Driver's birthdate in YYYY-MM-DD format.
    """

    driving_percentage: int = pydantic.Field()
    """
    Percentage of driving for this driver. Valid values are 25, 50, 75, or 100. The sum of all drivers' percentages must equal 100.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
