# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.paginated_policy_response import PaginatedPolicyResponse
from ..types.policy import Policy
from .raw_client import AsyncRawPoliciesClient, RawPoliciesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PoliciesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPoliciesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPoliciesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPoliciesClient
        """
        return self._raw_client

    def show_policy(self, car_policy: int, *, request_options: typing.Optional[RequestOptions] = None) -> Policy:
        """
        Show a specific policy

        Parameters
        ----------
        car_policy : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Policy
            Success

        Examples
        --------
        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.policies.show_policy(
            car_policy=1,
        )
        """
        _response = self._raw_client.show_policy(car_policy, request_options=request_options)
        return _response.data

    def list_policies(
        self,
        *,
        quote_request_id: typing.Optional[int] = None,
        quote_price_id: typing.Optional[str] = None,
        provider_policy_id: typing.Optional[int] = None,
        car_sequence_number: typing.Optional[str] = None,
        new_owner_id: typing.Optional[str] = None,
        previous_owner_id: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        min_price: typing.Optional[float] = None,
        max_price: typing.Optional[float] = None,
        per_page: typing.Optional[int] = None,
        date_from: typing.Optional[dt.date] = None,
        date_to: typing.Optional[dt.date] = None,
        include_aggregates: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedPolicyResponse:
        """
        Listing requested policies

        Parameters
        ----------
        quote_request_id : typing.Optional[int]

        quote_price_id : typing.Optional[str]

        provider_policy_id : typing.Optional[int]

        car_sequence_number : typing.Optional[str]

        new_owner_id : typing.Optional[str]

        previous_owner_id : typing.Optional[str]

        status : typing.Optional[int]

        min_price : typing.Optional[float]

        max_price : typing.Optional[float]

        per_page : typing.Optional[int]

        date_from : typing.Optional[dt.date]
            Inclusive lower bound for the policy date. For issued policies (`status=1`), this filters by `uploaded_at` (the provider policy issue timestamp) and falls back to `created_at` when `uploaded_at` is unavailable. For other statuses, this filters by `created_at`.

        date_to : typing.Optional[dt.date]
            Inclusive upper bound for the policy date. For issued policies (`status=1`), this filters by `uploaded_at` (the provider policy issue timestamp) and falls back to `created_at` when `uploaded_at` is unavailable. For other statuses, this filters by `created_at`.

        include_aggregates : typing.Optional[bool]
            When true, includes policy totals, total price, and monthly buckets for the filtered result set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedPolicyResponse
            Success

        Examples
        --------
        import datetime

        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.policies.list_policies(
            date_from=datetime.date.fromisoformat(
                "2026-06-01",
            ),
            date_to=datetime.date.fromisoformat(
                "2026-06-30",
            ),
            include_aggregates=True,
        )
        """
        _response = self._raw_client.list_policies(
            quote_request_id=quote_request_id,
            quote_price_id=quote_price_id,
            provider_policy_id=provider_policy_id,
            car_sequence_number=car_sequence_number,
            new_owner_id=new_owner_id,
            previous_owner_id=previous_owner_id,
            status=status,
            min_price=min_price,
            max_price=max_price,
            per_page=per_page,
            date_from=date_from,
            date_to=date_to,
            include_aggregates=include_aggregates,
            request_options=request_options,
        )
        return _response.data

    def issue_policy(
        self,
        *,
        otp: str,
        quote_request_id: int,
        quote_reference_id: str,
        quote_price_id: str,
        benefits: typing.Optional[typing.Sequence[str]] = OMIT,
        extra_fields: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Policy:
        """
        For issuing a new policy

        Parameters
        ----------
        otp : str
            The OTP received by the customer from the Issue OTP API

        quote_request_id : int
            ID of the car quote request

        quote_reference_id : str
            Unique identifier for the quote reference ID (coming from POST /quote-requests)

        quote_price_id : str
            Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)

        benefits : typing.Optional[typing.Sequence[str]]
            List of benefit UUIDs

        extra_fields : typing.Optional[typing.Dict[str, typing.Any]]
            Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Policy
            Created

        Examples
        --------
        from yasminaai import YasminaaiApi

        client = YasminaaiApi(
            token="YOUR_TOKEN",
        )
        client.policies.issue_policy(
            otp="123456",
            quote_request_id=123,
            quote_reference_id="550e8400-e29b-41d4-a716-446655440000",
            quote_price_id="550e8400-e29b-41d4-a716-446655440001",
        )
        """
        _response = self._raw_client.issue_policy(
            otp=otp,
            quote_request_id=quote_request_id,
            quote_reference_id=quote_reference_id,
            quote_price_id=quote_price_id,
            benefits=benefits,
            extra_fields=extra_fields,
            request_options=request_options,
        )
        return _response.data


class AsyncPoliciesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPoliciesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPoliciesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPoliciesClient
        """
        return self._raw_client

    async def show_policy(self, car_policy: int, *, request_options: typing.Optional[RequestOptions] = None) -> Policy:
        """
        Show a specific policy

        Parameters
        ----------
        car_policy : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Policy
            Success

        Examples
        --------
        import asyncio

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.policies.show_policy(
                car_policy=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.show_policy(car_policy, request_options=request_options)
        return _response.data

    async def list_policies(
        self,
        *,
        quote_request_id: typing.Optional[int] = None,
        quote_price_id: typing.Optional[str] = None,
        provider_policy_id: typing.Optional[int] = None,
        car_sequence_number: typing.Optional[str] = None,
        new_owner_id: typing.Optional[str] = None,
        previous_owner_id: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        min_price: typing.Optional[float] = None,
        max_price: typing.Optional[float] = None,
        per_page: typing.Optional[int] = None,
        date_from: typing.Optional[dt.date] = None,
        date_to: typing.Optional[dt.date] = None,
        include_aggregates: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedPolicyResponse:
        """
        Listing requested policies

        Parameters
        ----------
        quote_request_id : typing.Optional[int]

        quote_price_id : typing.Optional[str]

        provider_policy_id : typing.Optional[int]

        car_sequence_number : typing.Optional[str]

        new_owner_id : typing.Optional[str]

        previous_owner_id : typing.Optional[str]

        status : typing.Optional[int]

        min_price : typing.Optional[float]

        max_price : typing.Optional[float]

        per_page : typing.Optional[int]

        date_from : typing.Optional[dt.date]
            Inclusive lower bound for the policy date. For issued policies (`status=1`), this filters by `uploaded_at` (the provider policy issue timestamp) and falls back to `created_at` when `uploaded_at` is unavailable. For other statuses, this filters by `created_at`.

        date_to : typing.Optional[dt.date]
            Inclusive upper bound for the policy date. For issued policies (`status=1`), this filters by `uploaded_at` (the provider policy issue timestamp) and falls back to `created_at` when `uploaded_at` is unavailable. For other statuses, this filters by `created_at`.

        include_aggregates : typing.Optional[bool]
            When true, includes policy totals, total price, and monthly buckets for the filtered result set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedPolicyResponse
            Success

        Examples
        --------
        import asyncio
        import datetime

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.policies.list_policies(
                date_from=datetime.date.fromisoformat(
                    "2026-06-01",
                ),
                date_to=datetime.date.fromisoformat(
                    "2026-06-30",
                ),
                include_aggregates=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_policies(
            quote_request_id=quote_request_id,
            quote_price_id=quote_price_id,
            provider_policy_id=provider_policy_id,
            car_sequence_number=car_sequence_number,
            new_owner_id=new_owner_id,
            previous_owner_id=previous_owner_id,
            status=status,
            min_price=min_price,
            max_price=max_price,
            per_page=per_page,
            date_from=date_from,
            date_to=date_to,
            include_aggregates=include_aggregates,
            request_options=request_options,
        )
        return _response.data

    async def issue_policy(
        self,
        *,
        otp: str,
        quote_request_id: int,
        quote_reference_id: str,
        quote_price_id: str,
        benefits: typing.Optional[typing.Sequence[str]] = OMIT,
        extra_fields: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Policy:
        """
        For issuing a new policy

        Parameters
        ----------
        otp : str
            The OTP received by the customer from the Issue OTP API

        quote_request_id : int
            ID of the car quote request

        quote_reference_id : str
            Unique identifier for the quote reference ID (coming from POST /quote-requests)

        quote_price_id : str
            Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)

        benefits : typing.Optional[typing.Sequence[str]]
            List of benefit UUIDs

        extra_fields : typing.Optional[typing.Dict[str, typing.Any]]
            Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Policy
            Created

        Examples
        --------
        import asyncio

        from yasminaai import AsyncYasminaaiApi

        client = AsyncYasminaaiApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.policies.issue_policy(
                otp="123456",
                quote_request_id=123,
                quote_reference_id="550e8400-e29b-41d4-a716-446655440000",
                quote_price_id="550e8400-e29b-41d4-a716-446655440001",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.issue_policy(
            otp=otp,
            quote_request_id=quote_request_id,
            quote_reference_id=quote_reference_id,
            quote_price_id=quote_price_id,
            benefits=benefits,
            extra_fields=extra_fields,
            request_options=request_options,
        )
        return _response.data
