# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.paginated_policy_response import PaginatedPolicyResponse
from ..types.policy import Policy
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPoliciesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def show_policy(
        self, car_policy: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Policy]:
        """
        Show a specific policy

        Parameters
        ----------
        car_policy : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Policy]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"policies/{encode_path_param(car_policy)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Policy,
                    parse_obj_as(
                        type_=Policy,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_policies(
        self,
        *,
        quote_request_id: typing.Optional[int] = None,
        quote_price_id: typing.Optional[str] = None,
        provider_policy_id: typing.Optional[int] = None,
        car_sequence_number: typing.Optional[str] = None,
        new_owner_id: typing.Optional[str] = None,
        previous_owner_id: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        min_price: typing.Optional[float] = None,
        max_price: typing.Optional[float] = None,
        per_page: typing.Optional[int] = None,
        date_from: typing.Optional[dt.date] = None,
        date_to: typing.Optional[dt.date] = None,
        include_aggregates: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedPolicyResponse]:
        """
        Listing requested policies

        Parameters
        ----------
        quote_request_id : typing.Optional[int]

        quote_price_id : typing.Optional[str]

        provider_policy_id : typing.Optional[int]

        car_sequence_number : typing.Optional[str]

        new_owner_id : typing.Optional[str]

        previous_owner_id : typing.Optional[str]

        status : typing.Optional[int]

        min_price : typing.Optional[float]

        max_price : typing.Optional[float]

        per_page : typing.Optional[int]

        date_from : typing.Optional[dt.date]
            Inclusive lower bound for the policy date. For issued policies (`status=1`), this filters by `uploaded_at` (the provider policy issue timestamp) and falls back to `created_at` when `uploaded_at` is unavailable. For other statuses, this filters by `created_at`.

        date_to : typing.Optional[dt.date]
            Inclusive upper bound for the policy date. For issued policies (`status=1`), this filters by `uploaded_at` (the provider policy issue timestamp) and falls back to `created_at` when `uploaded_at` is unavailable. For other statuses, this filters by `created_at`.

        include_aggregates : typing.Optional[bool]
            When true, includes policy totals, total price, and monthly buckets for the filtered result set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedPolicyResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "policies",
            method="GET",
            params={
                "quote_request_id": quote_request_id,
                "quote_price_id": quote_price_id,
                "provider_policy_id": provider_policy_id,
                "car_sequence_number": car_sequence_number,
                "new_owner_id": new_owner_id,
                "previous_owner_id": previous_owner_id,
                "status": status,
                "min_price": min_price,
                "max_price": max_price,
                "per_page": per_page,
                "date_from": str(date_from) if date_from is not None else None,
                "date_to": str(date_to) if date_to is not None else None,
                "include_aggregates": include_aggregates,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedPolicyResponse,
                    parse_obj_as(
                        type_=PaginatedPolicyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def issue_policy(
        self,
        *,
        otp: str,
        quote_request_id: int,
        quote_reference_id: str,
        quote_price_id: str,
        benefits: typing.Optional[typing.Sequence[str]] = OMIT,
        extra_fields: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Policy]:
        """
        For issuing a new policy

        Parameters
        ----------
        otp : str
            The OTP received by the customer from the Issue OTP API

        quote_request_id : int
            ID of the car quote request

        quote_reference_id : str
            Unique identifier for the quote reference ID (coming from POST /quote-requests)

        quote_price_id : str
            Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)

        benefits : typing.Optional[typing.Sequence[str]]
            List of benefit UUIDs

        extra_fields : typing.Optional[typing.Dict[str, typing.Any]]
            Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Policy]
            Created
        """
        _response = self._client_wrapper.httpx_client.request(
            "policies",
            method="POST",
            json={
                "otp": otp,
                "quote_request_id": quote_request_id,
                "quote_reference_id": quote_reference_id,
                "quote_price_id": quote_price_id,
                "benefits": benefits,
                "extra_fields": extra_fields,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Policy,
                    parse_obj_as(
                        type_=Policy,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Dict[str, typing.Any],
                        parse_obj_as(
                            type_=typing.Dict[str, typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPoliciesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def show_policy(
        self, car_policy: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Policy]:
        """
        Show a specific policy

        Parameters
        ----------
        car_policy : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Policy]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"policies/{encode_path_param(car_policy)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Policy,
                    parse_obj_as(
                        type_=Policy,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_policies(
        self,
        *,
        quote_request_id: typing.Optional[int] = None,
        quote_price_id: typing.Optional[str] = None,
        provider_policy_id: typing.Optional[int] = None,
        car_sequence_number: typing.Optional[str] = None,
        new_owner_id: typing.Optional[str] = None,
        previous_owner_id: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        min_price: typing.Optional[float] = None,
        max_price: typing.Optional[float] = None,
        per_page: typing.Optional[int] = None,
        date_from: typing.Optional[dt.date] = None,
        date_to: typing.Optional[dt.date] = None,
        include_aggregates: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedPolicyResponse]:
        """
        Listing requested policies

        Parameters
        ----------
        quote_request_id : typing.Optional[int]

        quote_price_id : typing.Optional[str]

        provider_policy_id : typing.Optional[int]

        car_sequence_number : typing.Optional[str]

        new_owner_id : typing.Optional[str]

        previous_owner_id : typing.Optional[str]

        status : typing.Optional[int]

        min_price : typing.Optional[float]

        max_price : typing.Optional[float]

        per_page : typing.Optional[int]

        date_from : typing.Optional[dt.date]
            Inclusive lower bound for the policy date. For issued policies (`status=1`), this filters by `uploaded_at` (the provider policy issue timestamp) and falls back to `created_at` when `uploaded_at` is unavailable. For other statuses, this filters by `created_at`.

        date_to : typing.Optional[dt.date]
            Inclusive upper bound for the policy date. For issued policies (`status=1`), this filters by `uploaded_at` (the provider policy issue timestamp) and falls back to `created_at` when `uploaded_at` is unavailable. For other statuses, this filters by `created_at`.

        include_aggregates : typing.Optional[bool]
            When true, includes policy totals, total price, and monthly buckets for the filtered result set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedPolicyResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "policies",
            method="GET",
            params={
                "quote_request_id": quote_request_id,
                "quote_price_id": quote_price_id,
                "provider_policy_id": provider_policy_id,
                "car_sequence_number": car_sequence_number,
                "new_owner_id": new_owner_id,
                "previous_owner_id": previous_owner_id,
                "status": status,
                "min_price": min_price,
                "max_price": max_price,
                "per_page": per_page,
                "date_from": str(date_from) if date_from is not None else None,
                "date_to": str(date_to) if date_to is not None else None,
                "include_aggregates": include_aggregates,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedPolicyResponse,
                    parse_obj_as(
                        type_=PaginatedPolicyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def issue_policy(
        self,
        *,
        otp: str,
        quote_request_id: int,
        quote_reference_id: str,
        quote_price_id: str,
        benefits: typing.Optional[typing.Sequence[str]] = OMIT,
        extra_fields: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Policy]:
        """
        For issuing a new policy

        Parameters
        ----------
        otp : str
            The OTP received by the customer from the Issue OTP API

        quote_request_id : int
            ID of the car quote request

        quote_reference_id : str
            Unique identifier for the quote reference ID (coming from POST /quote-requests)

        quote_price_id : str
            Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)

        benefits : typing.Optional[typing.Sequence[str]]
            List of benefit UUIDs

        extra_fields : typing.Optional[typing.Dict[str, typing.Any]]
            Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Policy]
            Created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "policies",
            method="POST",
            json={
                "otp": otp,
                "quote_request_id": quote_request_id,
                "quote_reference_id": quote_reference_id,
                "quote_price_id": quote_price_id,
                "benefits": benefits,
                "extra_fields": extra_fields,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Policy,
                    parse_obj_as(
                        type_=Policy,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Dict[str, typing.Any],
                        parse_obj_as(
                            type_=typing.Dict[str, typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
